### ISSUE TITLE
Wrong documentation

### ISSUE THREAD

**Issue by tflx** [aerobatic/aerobatic-cli#1]
The documentation on the +New website link tells me to install:
`$ npm install aero-cli -g`
That does not exist - "aerobatic-cli" does however (obviously) but is that the same?
Continuing with aerobatic-cli instead I try `aero create` which needs an API key. Again your documentation says nothing about this.

**Comment by dvonlehman** [comment]
The npm module name has been corrected in the Aerobatic dashboard.
